### ISSUE TITLE
Bug - Breaking lineage due to alias

### ISSUE THREAD

**Issue by mattxxi** [b-ned/dbt-colibri#13]
**Configuration:**
    "dbt-colibri>=0.2.4",
    "dbt-core>=1.9.4",
    "dbt-snowflake>=1.9.4",

**Context:**
I have some silver models (between bronze model and gold model) that are classified as Unknown. there are not problem with the gold and bronze models, just the model in the middle.

**What I found:**
I managed to find out, when I create an alias in dbt model then they are classified as Unknown but if I remove it then everything works normally.

Somewhere in the code you might use the alias to build the lineage instead of the model name that would explain why the lineage breaks.

**Illustration:**
Models classified as unknown when set alias:

<img width="185" height="331" alt="Image" src="https://github.com/user-attachments/assets/f8e0476b-37f1-4259-b756-6d01cc318241" />

If I remove the alias for the staging people then it works:

<img width="422" height="140" alt="Image" src="https://github.com/user-attachments/assets/ce5dee12-1ccd-421d-a288-fa16c91169b3" />

dbt code:

```yml
version: 2

models:
  - name: ref_main_people__stg_people
    config:
      # database: ref_main_{{target.name}}
      # schema: people
      # snowflake_warehouse: dbt_wh_{{target.name}}_xs
      alias: stg_people
      materialized: view
```

**Comment by b-ned** [comment]
Hi @mattxxi,

Thanks for raising the issue, when using setting an alias the compiled SQL will change:

I reproduced the bug, and the column lineage parser was indeed looking for the table name, not the alias.
Should be fixed 
stg_customers with alias:

models:
  - name: stg_customers
    description: Customer data with basic cleaning and transformation applied, one row per customer.
    config:
      alias: stg_customer_alias
    columns:
      - name: customer_id
        description: The unique key for each customer.
        data_tests:
          - not_null
          - unique



<img width="591" height="432" alt="Image" src="https://github.com/user-attachments/assets/d490f7a4-2f74-4f55-a428-b1c2c1d2d91b" />

**Comment by mattxxi** [comment]
@b-ned 

With the new release I do not have the warnings anymore but it is still not working in the UI, the models are still unknown and the lineage is broken with alias.

<img width="650" height="378" alt="Image" src="https://github.com/user-attachments/assets/77ec7aa1-2af3-47cf-b694-e4e679315513" />

I will let you reopen this issue.

Thanks !

**Comment by b-ned** [comment]
Hi @mattxxi,

I've released a new version `0.2.6b1`, using `relation_name` to parse column lineage, and if there is no column lineage, it falls back (more robustly) to table lineage. I've tested on my end with aliases and on my end it looks ok. Could you verify?

If you still see issues, would you be able to run with the --debug flag? And provide (an anonamized) `colibri-manifest.json`&`manifest.json` snippet of the relavant models (`ref_main_stg_people`, plus `ref_main_people_ref_contact`)
